export const ActionTypes = {
 GETEMPLOYEELIST: 'GETEMPLOYEELIST',
 EDITEMPLOYEE: 'EDITEMPLOYEE',
 DELETEEMPLOYEE: 'DELETEEMPLOYEE',
 ADDEMPLOYEE: 'ADDEMPLOYEE',
 VIEWEMPLOYEE: 'VIEWEMPLOYEE',
 FILTEREMPLOYEE: 'FILTEREMPLOYEE',
 
}

